/*
 * tw5-bridge.js — injected into TiddlyWiki5 pages by the file-backups
 * extension's content script. Runs in the page's JavaScript context so it can
 * reach `$tw.wiki`.
 *
 * Provides two "arming" flows that piggyback on TW's normal tm-save-wiki:
 *
 *   Save As — toolbar button writes `$:/temp/plugins/file-backups/next-
 *     saveAs = "yes"` and dispatches tm-save-wiki. When TW then fires
 *     tiddlyfox-save-file on the messagebox, the bridge's capture-phase
 *     listener reads the temp tiddler and sets data-tiddlyfox-saveas on
 *     the messagebox synchronously, before the content script's bubble-
 *     phase listener reads it. Content script forwards saveas:"yes" to
 *     background → downloadDialog → native Save As dialog.
 *
 *   Milestone — modal/CP form writes next-milestone-{label,ts} temp
 *     tiddlers and dispatches tm-save-wiki. The same capture-phase
 *     listener transfers those values onto data-file-backups-milestone*
 *     attributes. Content script forwards them as msg.milestone* fields.
 *     Background's createMilestoneFile() writes a separate timestamped
 *     file alongside the Tower-of-Hanoi rotation in the backup dir.
 *
 * The capture-phase approach is deliberate: `$tw.wiki.addEventListener("change", ...)`
 * fires asynchronously, too late to influence the save already in flight.
 *
 * UI tiddlers (toolbar buttons, shortcut recipes, modal, CP form, readme,
 * license, keyboard config) are shipped as native TW .tid files under
 * addon/tiddlers/. An indexer (build-tools/index-tiddlers.js, run as a
 * pre-script before web-ext) writes tiddlers/index.json, which the bridge
 * fetches at install time, then loads each .tid via the standard TW
 * header/body parser. Authoring stays in real .tid files (drag in/out of
 * TW round-trips) instead of hand-escaped strings inside this JS file.
 */

(function () {
	"use strict";

	// Capture our own URL synchronously while the script is still running —
	// document.currentScript becomes null once the IIFE returns.
	var SCRIPT_SRC = (document.currentScript && document.currentScript.src) || "";
	var BASE_URL = SCRIPT_SRC.replace(/[^/]*$/, "");

	// When the extension is disabled or reinstalled, content scripts and the
	// background are torn down but page-context scripts (this file) are not —
	// the bridge from the previous extension lifecycle stays bound to the
	// messagebox. The newly-injected content script then loads a SECOND bridge
	// instance, which would attach a second capture-phase listener. Both fire
	// per save: the first reads the temp tiddler and deletes it, the second
	// reads undefined and overwrites data-tiddlyfox-saveas back to "no".
	// Result: Save As silently degrades to normal save until F5.
	// Detect the prior instance and bail.
	if (window.__fileBackupsBridgeInstalled) {
		return;
	}
	window.__fileBackupsBridgeInstalled = true;

	// Tiddler assets are auto-discovered via a manifest at
	// tiddlers/index.json, generated by build-tools/index-tiddlers.js (runs
	// as a pre-script before web-ext run / build). Two arrays:
	//   real   — top-level .tid files in addon/tiddlers/ become real
	//            tiddlers, overwriting on every page load. All under
	//            $:/temp/* so they're wiped on F5 and don't dirty the wiki.
	//            Used for tiddlers that drive widget refresh (toolbar
	//            buttons, $:/tags/KeyboardShortcut action recipes).
	//   shadow — .tid files under addon/tiddlers/plugin/** are bundled
	//            into a runtime plugin and registered as shadows. Used
	//            for tiddlers whose titles must live OUTSIDE $:/temp/ —
	//            the keyboard-manager config tiddlers at fixed paths
	//            ($:/config/shortcuts/<name>, $:/config/ShortcutInfo/
	//            <name>, $:/config/PageControlButtons/Visibility/<title>)
	//            plus the standard plugin-style readme and license. As
	//            shadows they don't trigger SaverFilter and auto-defer to
	//            any real tiddler the user later creates at the same
	//            title — so user customisation overrides our defaults
	//            without any extra guard logic on our side.
	// The plugin wrapper itself lives at $:/temp/* so it doesn't dirty
	// either, and uses a non-standard plugin-type so it stays out of
	// Control Panel > Plugins.
	var INDEX_FILE = "tiddlers/index.json";
	var SHADOW_BUNDLE_TITLE = "$:/temp/plugins/file-backups/config";
	var SHADOW_BUNDLE_TYPE = "file-backups-assets";

	var retries = 0;
	function waitForReady() {
		// $tw.boot.executedStartupModules.story is set true when the
		// `story` startup module finishes (it declares `after: ["startup"]`,
		// so by the time it runs, $tw.wiki + plugins + macros are all in
		// place). Tighter gate than just `$tw.wiki.addTiddler` existence,
		// which is true much earlier during boot.
		var twReady = typeof $tw !== "undefined"
			&& $tw.boot
			&& $tw.boot.executedStartupModules
			&& $tw.boot.executedStartupModules.story === true;
		var boxReady = !!document.getElementById("tiddlyfox-message-box");
		if (twReady && boxReady) {
			install();
			return;
		}
		if (retries++ > 100) return; // ~5s
		setTimeout(waitForReady, 50);
	}
	waitForReady();

	async function install() {
		try {
			attachSaveListener();
			attachMilestoneFlashCleanup();
			attachTestInjectListener();
			var index = await fetch(BASE_URL + INDEX_FILE).then(function (r) { return r.json(); });
			await Promise.all([
				installTiddlersFromAssets(index.real || []),
				installShadowBundleFromAssets(index.shadow || [], SHADOW_BUNDLE_TITLE, SHADOW_BUNDLE_TYPE)
			]);
		} catch (err) {
			console.log("[fb-bridge] install failed:", err);
		}
	}

	// Dev test affordance (beta builds only — the test/ shadow folder is
	// stripped from stable builds by the build-time gate). The CP test buttons
	// write "stable" or "beta" to a temp tiddler; we observe the change, fire
	// a CustomEvent on the messagebox so the content script can forward to
	// background, and delete the temp so re-clicks re-fire the event.
	function attachTestInjectListener() {
		var TEST_TITLE = "$:/temp/plugins/file-backups/test/inject-update";
		$tw.wiki.addEventListener("change", function (changes) {
			if (!changes[TEST_TITLE]) return;
			var t = $tw.wiki.getTiddler(TEST_TITLE);
			if (!t) return; // deletion event from our own cleanup below
			var kind = t.fields.text;
			if (kind !== "stable" && kind !== "beta") return;
			var box = document.getElementById("tiddlyfox-message-box");
			if (box) {
				box.dispatchEvent(new CustomEvent("file-backups-test-inject", {detail: {kind: kind}}));
			}
			$tw.wiki.deleteTiddler(TEST_TITLE);
		});
	}

	// When the milestone flash animation finishes (after its 3 keyframe
	// iterations), wipe the just-saved state tiddler so the same entry
	// doesn't re-flash on every subsequent modal open / CP render. Filtering
	// on animationName makes the listener inert for any other animations on
	// the page.
	function attachMilestoneFlashCleanup() {
		document.addEventListener("animationend", function (e) {
			if (e.animationName === "fb-milestone-flash" &&
				typeof $tw !== "undefined" && $tw.wiki && typeof $tw.wiki.deleteTiddler === "function") {
				$tw.wiki.deleteTiddler("$:/temp/plugins/file-backups/milestone/just-saved");
			}
		});
	}

	// .tid parser — matches TW's own application/x-tiddler deserializer
	// (boot/boot.js parseFields + the .tid case). Standard format is:
	//   key: value
	//   key: value
	//   <blank line>
	//   <text body up to EOF>
	// A file with no blank line is treated as all headers (no body), so a
	// "text:" header line can stand in for the body. Lines starting with
	// "#" are comments.
	function parseTid(raw) {
		var split = raw.split(/\r?\n\r?\n/mg);
		var fields = {};
		if (split.length >= 1) {
			parseFields(split[0], fields);
		}
		if (split.length >= 2) {
			fields.text = split.slice(1).join("\n\n");
		}
		return fields;
	}

	function parseFields(text, fields) {
		text.split(/\r?\n/mg).forEach(function (line) {
			if (line.charAt(0) !== "#") {
				var p = line.indexOf(":");
				if (p !== -1) {
					var field = line.substr(0, p).trim(),
						value = line.substr(p + 1).trim();
					if (field) fields[field] = value;
				}
			}
		});
		return fields;
	}

	async function installTiddlersFromAssets(files) {
		await Promise.all(files.map(async function (path) {
			var raw = await fetch(BASE_URL + path).then(function (r) { return r.text(); });
			var fields = parseTid(raw);
			$tw.wiki.addTiddler(new $tw.Tiddler(fields));
		}));
	}

	// Bundle a set of .tid assets into a runtime plugin so their tiddlers
	// become shadows in the wiki. Used for tiddlers whose titles must live
	// outside $:/temp/ but which we don't want to dirty the wiki — shadows
	// are read by getTiddlerText / getTiddlersWithTag the same as real
	// tiddlers, but they don't trigger SaverFilter and they auto-defer to
	// any real tiddler the user later creates at the same title.
	async function installShadowBundleFromAssets(files, wrapperTitle, pluginType) {
		var pluginContents = {tiddlers: {}};
		await Promise.all(files.map(async function (path) {
			var raw = await fetch(BASE_URL + path).then(function (r) { return r.text(); });
			var fields = parseTid(raw);
			if (fields.title) {
				pluginContents.tiddlers[fields.title] = fields;
			}
		}));
		$tw.wiki.addTiddler(new $tw.Tiddler({
			title: wrapperTitle,
			type: "application/json",
			"plugin-type": pluginType,
			text: JSON.stringify(pluginContents)
		}));
		$tw.wiki.readPluginInfo([wrapperTitle]);
		$tw.wiki.registerPluginTiddlers(pluginType, [wrapperTitle]);
		$tw.wiki.unpackPluginTiddlers();
		// Notify keyboard-manager / other listeners that the shadow set
		// changed so they re-cache. Keyboard manager's handleShortcutChanges
		// includes detectNewShortcuts which watches $:/config/shortcuts/
		// prefix changes — both shadow and real changes flow through the
		// same change-event pipeline.
		Object.keys(pluginContents.tiddlers).forEach(function (title) {
			$tw.wiki.enqueueTiddlerEvent(title, false, true);
		});
	}

	// Capture-phase listener runs before the content-script's bubble-phase
	// listener on the same element, so the attribute it writes is visible when
	// the content script reads it.
	function attachSaveListener() {
		var box = document.getElementById("tiddlyfox-message-box");
		box.addEventListener("tiddlyfox-save-file", function () {
			// Save As arming
			var saveAsT = $tw.wiki.getTiddler("$:/temp/plugins/file-backups/next-saveAs");
			var saveAsArmed = !!(saveAsT && saveAsT.fields.text === "yes");
			box.setAttribute("data-tiddlyfox-saveas", saveAsArmed ? "yes" : "no");
			if (saveAsArmed) {
				$tw.wiki.deleteTiddler("$:/temp/plugins/file-backups/next-saveAs");
			}

			// Milestone arming. The form action sets two temp tiddlers
			// synchronously before dispatching tm-save-wiki, so both are in
			// place by the time TW's tiddlyfox saver fires this event.
			var labelT = $tw.wiki.getTiddler("$:/temp/plugins/file-backups/next-milestone-label");
			var tsT = $tw.wiki.getTiddler("$:/temp/plugins/file-backups/next-milestone-ts");
			var milestoneArmed = !!(tsT && tsT.fields.text);
			box.setAttribute("data-file-backups-milestone", milestoneArmed ? "yes" : "no");
			if (milestoneArmed) {
				box.setAttribute("data-file-backups-milestone-label", (labelT && labelT.fields.text) || "");
				box.setAttribute("data-file-backups-milestone-ts", tsT.fields.text);
				$tw.wiki.deleteTiddler("$:/temp/plugins/file-backups/next-milestone-label");
				$tw.wiki.deleteTiddler("$:/temp/plugins/file-backups/next-milestone-ts");
			}
		}, true);
	}
})();
