/*
 * tw5-bridge.js — injected into TiddlyWiki5 pages by the file-backups
 * extension's content script. Runs in the page's JavaScript context so it can
 * reach `$tw.wiki`.
 *
 * Installs a "save as" toolbar button. Clicking it sets
 * `$:/temp/plugins/file-backups/next-saveAs = "yes"` and dispatches the normal TW
 * save (`tm-save-wiki`). When TW then fires `tiddlyfox-save-file` on the
 * messagebox, this bridge's capture-phase listener runs first, reads the temp
 * tiddler, and sets `data-tiddlyfox-saveas` on the messagebox synchronously.
 * The content script's existing bubble-phase listener then reads that
 * attribute and forwards `msg.saveas = "yes"` to the background, which opens
 * the native Save As dialog. The temp tiddler is cleared on consumption.
 *
 * The capture-phase approach is deliberate: `$tw.wiki.addEventListener("change", ...)`
 * fires asynchronously, too late to influence the save already in flight.
 *
 * UI tiddlers (button, shortcut recipes, readme, license) are shipped as
 * native TW .tid files under addon/tiddlers/. The bridge fetches them at
 * install time, parses the standard TW header/body format, and addTiddler-s
 * each. Authors edit real .tid files (drag in/out of TW round-trips cleanly)
 * instead of hand-escaped strings inside this JS file.
 */

(function () {
	"use strict";

	// Capture our own URL synchronously while the script is still running —
	// document.currentScript becomes null once the IIFE returns.
	var SCRIPT_SRC = (document.currentScript && document.currentScript.src) || "";
	var BASE_URL = SCRIPT_SRC.replace(/[^/]*$/, "");

	// When the extension is disabled or reinstalled, content scripts and the
	// background are torn down but page-context scripts (this file) are not —
	// the bridge from the previous extension lifecycle stays bound to the
	// messagebox. The newly-injected content script then loads a SECOND bridge
	// instance, which would attach a second capture-phase listener. Both fire
	// per save: the first reads the temp tiddler and deletes it, the second
	// reads undefined and overwrites data-tiddlyfox-saveas back to "no".
	// Result: Save As silently degrades to normal save until F5.
	// Detect the prior instance and bail.
	if (window.__fileBackupsBridgeInstalled) {
		return;
	}
	window.__fileBackupsBridgeInstalled = true;

	// Tiddler assets are auto-discovered via a manifest at
	// tiddlers/index.json, generated by build-tools/index-tiddlers.js (runs
	// as a pre-script before web-ext run / build). Two arrays:
	//   real   — top-level .tid files in addon/tiddlers/ become real
	//            tiddlers, overwriting on every page load. All under
	//            $:/temp/* so they're wiped on F5 and don't dirty the wiki.
	//            Used for tiddlers that drive widget refresh (toolbar
	//            buttons, $:/tags/KeyboardShortcut action recipes).
	//   shadow — .tid files under addon/tiddlers/plugin/** are bundled
	//            into a runtime plugin and registered as shadows. Used for
	//            tiddlers whose titles must live outside $:/temp/ (the
	//            keyboard-manager config tiddlers at fixed paths) and for
	//            informational tiddlers (readme/license) we don't want to
	//            re-emit on every page load. Shadows don't trigger
	//            SaverFilter and auto-defer to any real tiddler the user
	//            later creates at the same title.
	// The plugin wrapper itself lives at $:/temp/* so it doesn't dirty
	// either, and uses a non-standard plugin-type so it stays out of
	// Control Panel > Plugins.
	var INDEX_FILE = "tiddlers/index.json";
	var SHADOW_BUNDLE_TITLE = "$:/temp/plugins/file-backups/config";
	var SHADOW_BUNDLE_TYPE = "file-backups-assets";

	var retries = 0;
	function waitForReady() {
		var twReady = typeof $tw !== "undefined" && $tw.wiki && typeof $tw.wiki.addTiddler === "function";
		var boxReady = !!document.getElementById("tiddlyfox-message-box");
		if (twReady && boxReady) {
			install();
			return;
		}
		if (retries++ > 100) return; // ~5s
		setTimeout(waitForReady, 50);
	}
	waitForReady();

	async function install() {
		try {
			attachSaveListener();
			var index = await fetch(BASE_URL + INDEX_FILE).then(function (r) { return r.json(); });
			await Promise.all([
				installTiddlersFromAssets(index.real || []),
				installShadowBundleFromAssets(index.shadow || [], SHADOW_BUNDLE_TITLE, SHADOW_BUNDLE_TYPE)
			]);
		} catch (err) {
			console.log("[fb-bridge] install failed:", err);
		}
	}

	// .tid parser — matches TW's own application/x-tiddler deserializer
	// (boot/boot.js parseFields + the .tid case). Standard format is:
	//   key: value
	//   key: value
	//   <blank line>
	//   <text body up to EOF>
	// A file with no blank line is treated as all headers (no body), so a
	// "text:" header line can stand in for the body. Lines starting with
	// "#" are comments.
	function parseTid(raw) {
		var split = raw.split(/\r?\n\r?\n/mg);
		var fields = {};
		if (split.length >= 1) {
			parseFields(split[0], fields);
		}
		if (split.length >= 2) {
			fields.text = split.slice(1).join("\n\n");
		}
		return fields;
	}

	function parseFields(text, fields) {
		text.split(/\r?\n/mg).forEach(function (line) {
			if (line.charAt(0) !== "#") {
				var p = line.indexOf(":");
				if (p !== -1) {
					var field = line.substr(0, p).trim(),
						value = line.substr(p + 1).trim();
					if (field) fields[field] = value;
				}
			}
		});
		return fields;
	}

	async function installTiddlersFromAssets(files) {
		await Promise.all(files.map(async function (path) {
			var raw = await fetch(BASE_URL + path).then(function (r) { return r.text(); });
			var fields = parseTid(raw);
			$tw.wiki.addTiddler(new $tw.Tiddler(fields));
		}));
	}

	// Bundle a set of .tid assets into a runtime plugin so their tiddlers
	// become shadows in the wiki. Used for tiddlers whose titles must live
	// outside $:/temp/ but which we don't want to dirty the wiki — shadows
	// are read by getTiddlerText / getTiddlersWithTag the same as real
	// tiddlers, but they don't trigger SaverFilter and they auto-defer to
	// any real tiddler the user later creates at the same title.
	async function installShadowBundleFromAssets(files, wrapperTitle, pluginType) {
		var pluginContents = {tiddlers: {}};
		await Promise.all(files.map(async function (path) {
			var raw = await fetch(BASE_URL + path).then(function (r) { return r.text(); });
			var fields = parseTid(raw);
			if (fields.title) {
				pluginContents.tiddlers[fields.title] = fields;
			}
		}));
		$tw.wiki.addTiddler(new $tw.Tiddler({
			title: wrapperTitle,
			type: "application/json",
			"plugin-type": pluginType,
			text: JSON.stringify(pluginContents)
		}));
		$tw.wiki.readPluginInfo([wrapperTitle]);
		$tw.wiki.registerPluginTiddlers(pluginType, [wrapperTitle]);
		$tw.wiki.unpackPluginTiddlers();
		// Notify keyboard-manager / other listeners that the shadow set
		// changed so they re-cache. Keyboard manager's handleShortcutChanges
		// includes detectNewShortcuts which watches $:/config/shortcuts/
		// prefix changes — both shadow and real changes flow through the
		// same change-event pipeline.
		Object.keys(pluginContents.tiddlers).forEach(function (title) {
			$tw.wiki.enqueueTiddlerEvent(title, false, true);
		});
	}

	// Capture-phase listener runs before the content-script's bubble-phase
	// listener on the same element, so the attribute it writes is visible when
	// the content script reads it.
	function attachSaveListener() {
		var box = document.getElementById("tiddlyfox-message-box");
		box.addEventListener("tiddlyfox-save-file", function () {
			var t = $tw.wiki.getTiddler("$:/temp/plugins/file-backups/next-saveAs");
			var armed = !!(t && t.fields.text === "yes");
			box.setAttribute("data-tiddlyfox-saveas", armed ? "yes" : "no");
			if (armed) {
				$tw.wiki.deleteTiddler("$:/temp/plugins/file-backups/next-saveAs");
			}
		}, true);
	}
})();
